# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'saraui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SaraGui(object):
    def setupUi(self, SaraGui):
        SaraGui.setObjectName("SaraGui")
        SaraGui.resize(1128, 845)
        self.centralwidget = QtWidgets.QWidget(SaraGui)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1131, 851))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../../Pictures/Sara images/QmVacftCGVBnPJ5PzZR1b9aBJVAqi93bcGadxKP37CLVv1.gif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(480, 670, 201, 71))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(24)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(107, 206, 211);\n"
"border-bottom-color: rgb(24, 204, 159);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(970, 777, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.SplitHCursor))
        self.pushButton_2.setStyleSheet("background-color: rgb(27, 27, 27);\n"
"color: rgb(255, 0, 0);\n"
"\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        SaraGui.setCentralWidget(self.centralwidget)

        self.retranslateUi(SaraGui)
        QtCore.QMetaObject.connectSlotsByName(SaraGui)

    def retranslateUi(self, SaraGui):
        _translate = QtCore.QCoreApplication.translate
        SaraGui.setWindowTitle(_translate("SaraGui", "MainWindow"))
        self.pushButton.setText(_translate("SaraGui", " Activate >>"))
        self.pushButton_2.setText(_translate("SaraGui", "Terminate"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SaraGui = QtWidgets.QMainWindow()
    ui = Ui_SaraGui()
    ui.setupUi(SaraGui)
    SaraGui.show()
    sys.exit(app.exec_())
